binance_futures:
    key_id: 'xK4iBIDVfjkTlh5ajqjK1o5ujmtcOuy0xdK3EtpH2iUZRZXhvsuaSoOknN2c28vM'
    key_secret: '4tekstNiF8SbJhwTALpQV9KAJAiywgLngnA0gAYv9apRxjmrVrgnjmsID6G5MMTt'
bitmex:
    key_id: 'GiDbpgEBLGPrukiJb7St2bV_'
    key_secret: 'RrJYzZlq8wpAgVNcI2WCDHY8t_OUbC0r0zESNK6vFYA4ZVV4'
bitfinex:
    key_id: null
    key_secret: null
coinbase:
    key_id: null
    key_secret: null
    key_passphrase: null
poloniex:
    key_id: null
    key_secret: null
gemini:
    key_id: null
    key_secret: null
kraken:
    key_id: null
    key_secret: null
deribit:
    key_id: '-D5YHdyP'
    key_secret: 'abdFm3PY38AvLGtukEk8BZfvx2zxQGOWn8v6R7cL4e4'
ftx:
    ftx_coen:
        key_id: '_JtnzaJ0n1zbthMBoRZRFbBX7CK_2eZ0CncWcTDz'
        key_secret: 'Hr5yd4__8PRTj7sPYCnoz-PJjMVGNS8pDQHtkrc1'
    ftx_artur:
        key_id: 'CyTz3MvS3snUv3lSBeQ6AP0Jr9spnxf481G_Xs9X'
        key_secret: 'QC5Xtd9mk2J1YokSz0K8oZXtdKONX06V9o5-WiYt'
    ftx_government:
        key_id: 'ivQR71O1z0tgUJWdsuXsdATLMeoztuHFxo5bQX3l'
        key_secret: 'BRcEhnwDkMhbfj6N2sycms5jixLsGneBoycEg6cn'
